### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by OlehIlchyshyn** [OlehIlchyshyn/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by t1neoff** [comment]
## Education
#### 2018
National University "Lviv Polytechnic"
_Software Engineering, Institute of computer science and information technology_
#### 2015-2018
Lviv Physics and Mathematics Lyceum, Lviv, Ukraine
#### 2007-2015
Gymnasium "Hrono", Lviv, Ukraine

**Comment by t1neoff** [comment]
## Experience
No working experiece :(

**Comment by t1neoff** [comment]
<h3>Education</h3>
                  <ul class="timeline">
                    <li>
                      <div>2018 &ndash; <em>present</em></div>
                      <div>National University "Lviv Polytechnic"<br /><i>Software Engineering, Institute of computer science and information technology</i></div>
                    </li>
                    <br />
                    <li>
                      <div>2015 &ndash; 2018</div>
                      <div>Lviv Physics and Mathematics Lyceum, Lviv, Ukraine</div>
                    </li>
                    <li>
                      <div>2007 &ndash; 2015</div>
                      <div>Gymnasium "Hrono", Lviv, Ukraine</div>
                    </li>
                  </ul>

**Comment by t1neoff** [comment]
<h3>Experience</h3>
                <p>No working experience :( </p>
