### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by OlehIlchyshyn** [OlehIlchyshyn/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by t1neoff** [comment]
## Languages
* English -  _B2_
* Ukrainian -  _Native_
* Russian -  _Fluent_

**Comment by t1neoff** [comment]
## Technologies and skills
* C/C++
* Qt Framework + Creator
* Ruby on Rails
* Web stack (HTML/CSS/JS)
* Java
* JavaEE
* Unit testing
* Docker
* Algorithms knowledge
* OOP
* Design principles and patterns
* Operating systems and networking

**Comment by t1neoff** [comment]
<section>
                  <h3>Languages</h3>
                  <p class="tags small">
                    <p class="language">УКРАЇНСЬКА</p>
                    <p class="language">РУССКИЙ</p>
                    <p class="language">ENGLISH &mdash; B2</p>
                </section>

**Comment by t1neoff** [comment]
<section>
                  <h3>Skills</h3>
                  <p class="tags">C C++ QT RAILS JAVA JAVAEE JUNIT DOCKER HTML CSS JS BOOTSTRAP JQUERY <span class="nowrap">MICROSOFT OFFICE</span> PHOTOSHOP LINUX WINDOWS MYSQL POSTGRESQL MICROSOFT SQL NETWORKING</p>
                </section>

**Comment by t1neoff** [comment]
<section>
                  <h3>Traits</h3>
                  <p class="tags small">ADVENTUROUS FAIR LISTENER GREGARIOUS <a href="https://www.16personalities.com/uk/osobystist-enfj" rel="external">PROTAGONIS</a> AGNOSTIC PROCRASTINATOR PICKY</p>
                </section>

**Comment by t1neoff** [comment]
<section>
                  <h3>Likes&#x1f643;</h3>
                  <p class="tags small">CYCLING TRAVELLING MOUNTAINS PHOTOGRAPHY FORESTS FOOD MOVIES SERIES CATS LVIV INDIE ROCK TECHNOLOGIES></p>
                </section>

**Comment by t1neoff** [comment]
<section>
                  <h3>Dislikes&#x1f610;</h3>
                  <p class="tags small">CRITICISM RACISM OVERCONFIDENCE DISHONEST TV <span class="nowrap">BAD ROADS</span></p>
                </section>

**Comment by t1neoff** [comment]
<section>
                  <h3>Wants&#x1f644;</h3>
                  <p class="tags small bulleted"><span class="tag">TO HELP IMPROVE LIFE OF THE OTHERS</span><span class="tag">TO TRAVEL ACROSS EUROPE ON A BIKE</span><span class="tag">TO HAVE OPPORTUNITY TO TRAVEL MORE</span></p>
                </section>

**Comment by t1neoff** [comment]
<section>
                  <h3>Articles</h3>
                  <p>None published <sup><em>yet</em></sup></p>
                </section>
